/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUAudioRequest : NSObject {
    AVAudioPlayer * _audioPlayer;
    id  _completion;
    NSString * _label;
}

@property (nonatomic, retain) AVAudioPlayer *audioPlayer;
@property (nonatomic, copy) id completion;
@property (nonatomic, copy) NSString *label;

- (void).cxx_destruct;
- (id)audioPlayer;
- (id)completion;
- (id)label;
- (void)setAudioPlayer:(id)arg1;
- (void)setCompletion:(id)arg1;
- (void)setLabel:(id)arg1;

@end
