/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUBluetoothRelayMessage : NSObject {
    id  _completionHandler;
    NSString * _conduitDeviceID;
    NSString * _destinationAddress;
    NSData * _messageData;
    int  _messageType;
    NSString * _sourceAddress;
}

@property (nonatomic, copy) id completionHandler;
@property (nonatomic, copy) NSString *conduitDeviceID;
@property (nonatomic, copy) NSString *destinationAddress;
@property (nonatomic, copy) NSData *messageData;
@property (nonatomic) int messageType;
@property (nonatomic, copy) NSString *sourceAddress;

- (void).cxx_destruct;
- (id)completionHandler;
- (id)conduitDeviceID;
- (id)description;
- (id)destinationAddress;
- (id)messageData;
- (int)messageType;
- (void)setCompletionHandler:(id)arg1;
- (void)setConduitDeviceID:(id)arg1;
- (void)setDestinationAddress:(id)arg1;
- (void)setMessageData:(id)arg1;
- (void)setMessageType:(int)arg1;
- (void)setSourceAddress:(id)arg1;
- (id)sourceAddress;

@end
