/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUBluetoothClassicConnection : NSObject <CUReadWriteRequestable> {
    id  _activateCompletion;
    BOOL  _btConnected;
    IOBluetoothDevice * _btDevice;
    BOOL  _btDeviceAddrStr;
    unsigned int  _connectionFlags;
    BOOL  _connectionObserving;
    NSString * _destinationPeer;
    NSString * _destinationService;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    id  _errorHandler;
    BOOL  _invalidateCalled;
    BOOL  _invalidateDone;
    id  _invalidationHandler;
    CBL2CAPChannel * _l2capChannel;
    NSString * _label;
    unsigned int  _requiredServices;
    id  _serverInvalidationHandler;
    int  _state;
    NSObject<OS_dispatch_source> * _timeoutTimer;
    struct LogCategory { int x1; int x2; char *x3; unsigned int x4; char *x5; char *x6; int x7; struct LogCategory {} *x8; struct LogOutput {} *x9; struct LogOutput {} *x10; unsigned long long x11; unsigned long long x12; unsigned int x13; unsigned int x14; char *x15; struct LogCategoryPrivate {} *x16; } * _ucat;
}

@property (nonatomic) unsigned int connectionFlags;
@property (nonatomic, copy) NSString *destinationPeer;
@property (nonatomic, copy) NSString *destinationService;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (nonatomic, copy) id errorHandler;
@property (nonatomic, copy) id invalidationHandler;
@property (nonatomic, retain) CBL2CAPChannel *l2capChannel;
@property (nonatomic, copy) NSString *label;
@property (nonatomic) unsigned int requiredServices;
@property (nonatomic, copy) id serverInvalidationHandler;

- (void).cxx_destruct;
- (void)_connectionCompleteNotification:(id)arg1;
- (void)_externalInvokeBlock:(id)arg1;
- (id)_internalDispatchQueue;
- (void)_invalidate;
- (void)_invalidated;
- (void)_reportError:(id)arg1;
- (void)_run;
- (BOOL)_runConnectStart;
- (BOOL)_startConnectingAndReturnError:(id*)arg1;
- (void)_timeoutFired;
- (BOOL)activateDirectAndReturnError:(id*)arg1;
- (void)activateWithCompletion:(id)arg1;
- (void)connectionComplete:(id)arg1 status:(int)arg2;
- (unsigned int)connectionFlags;
- (void)dealloc;
- (id)destinationPeer;
- (id)destinationService;
- (id)dispatchQueue;
- (id)errorHandler;
- (id)init;
- (void)invalidate;
- (id)invalidationHandler;
- (id)l2capChannel;
- (id)label;
- (void)readWithRequest:(id)arg1;
- (unsigned int)requiredServices;
- (id)serverInvalidationHandler;
- (void)setConnectionFlags:(unsigned int)arg1;
- (void)setDestinationPeer:(id)arg1;
- (void)setDestinationService:(id)arg1;
- (void)setDispatchQueue:(id)arg1;
- (void)setErrorHandler:(id)arg1;
- (void)setInvalidationHandler:(id)arg1;
- (void)setL2capChannel:(id)arg1;
- (void)setLabel:(id)arg1;
- (void)setRequiredServices:(unsigned int)arg1;
- (void)setServerInvalidationHandler:(id)arg1;
- (void)writeWithRequest:(id)arg1;

@end
