/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUBluetoothUpdateAccessoryDevicesRequest : NSObject {
    NSString * _accessoryID;
    id  _completionHandler;
    NSArray * _deviceAddresses;
    unsigned int  _deviceState;
    int  _highPriorityState;
    int  _hijackState;
}

@property (nonatomic, copy) NSString *accessoryID;
@property (nonatomic, copy) id completionHandler;
@property (nonatomic, copy) NSArray *deviceAddresses;
@property (nonatomic) unsigned int deviceState;
@property (nonatomic) int highPriorityState;
@property (nonatomic) int hijackState;

- (void).cxx_destruct;
- (id)accessoryID;
- (id)completionHandler;
- (id)description;
- (id)deviceAddresses;
- (unsigned int)deviceState;
- (int)highPriorityState;
- (int)hijackState;
- (void)setAccessoryID:(id)arg1;
- (void)setCompletionHandler:(id)arg1;
- (void)setDeviceAddresses:(id)arg1;
- (void)setDeviceState:(unsigned int)arg1;
- (void)setHighPriorityState:(int)arg1;
- (void)setHijackState:(int)arg1;

@end
