/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUBLEScanner : NSObject <CBCentralManagerDelegate> {
    BOOL  _activateCalled;
    int  _bluetoothState;
    id  _bluetoothStateChangedHandler;
    CBCentralManager * _centralManager;
    unsigned int  _changeFlags;
    BOOL  _changesPending;
    id  _deviceChangedHandler;
    id  _deviceFoundHandler;
    id  _deviceLostHandler;
    NSMutableDictionary * _devices;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    BOOL  _invalidateCalled;
    BOOL  _invalidateDone;
    id  _invalidationHandler;
    NSString * _label;
    int  _rssiThreshold;
    unsigned int  _scanFlags;
    NSDictionary * _scanParametersCurrent;
    int  _scanRate;
    BOOL  _scannerStartCalled;
    CUSystemMonitor * _systemMonitor;
    struct LogCategory { int x1; int x2; char *x3; unsigned int x4; char *x5; char *x6; int x7; struct LogCategory {} *x8; struct LogOutput {} *x9; struct LogOutput {} *x10; unsigned long long x11; unsigned long long x12; unsigned int x13; unsigned int x14; char *x15; struct LogCategoryPrivate {} *x16; } * _ucat;
}

@property (nonatomic) int bluetoothState;
@property (nonatomic, copy) id bluetoothStateChangedHandler;
@property (nonatomic) unsigned int changeFlags;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, copy) id deviceChangedHandler;
@property (nonatomic, copy) id deviceFoundHandler;
@property (nonatomic, copy) id deviceLostHandler;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) id invalidationHandler;
@property (nonatomic, copy) NSString *label;
@property int rssiThreshold;
@property (nonatomic) unsigned int scanFlags;
@property (nonatomic) int scanRate;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_invalidate;
- (void)_invalidated;
- (id)_scanParameters;
- (id)_scanParametersSummary:(id)arg1;
- (BOOL)_shouldScan;
- (void)_stopScanIfNeededWithReason:(const char *)arg1;
- (void)_update;
- (void)_updateIfNeededWithBlock:(id)arg1;
- (void)_updateScanRules:(id*)arg1 payloadType:(unsigned char)arg2 rssiThreshold:(int)arg3;
- (void)activate;
- (int)bluetoothState;
- (id)bluetoothStateChangedHandler;
- (void)centralManager:(id)arg1 didDiscoverPeripheral:(id)arg2 advertisementData:(id)arg3 RSSI:(id)arg4;
- (void)centralManagerDidUpdateState:(id)arg1;
- (unsigned int)changeFlags;
- (void)dealloc;
- (id)deviceChangedHandler;
- (id)deviceFoundHandler;
- (id)deviceLostHandler;
- (id)dispatchQueue;
- (id)init;
- (void)invalidate;
- (id)invalidationHandler;
- (id)label;
- (int)rssiThreshold;
- (unsigned int)scanFlags;
- (int)scanRate;
- (void)setBluetoothState:(int)arg1;
- (void)setBluetoothStateChangedHandler:(id)arg1;
- (void)setChangeFlags:(unsigned int)arg1;
- (void)setDeviceChangedHandler:(id)arg1;
- (void)setDeviceFoundHandler:(id)arg1;
- (void)setDeviceLostHandler:(id)arg1;
- (void)setDispatchQueue:(id)arg1;
- (void)setInvalidationHandler:(id)arg1;
- (void)setLabel:(id)arg1;
- (void)setRssiThreshold:(int)arg1;
- (void)setScanFlags:(unsigned int)arg1;
- (void)setScanRate:(int)arg1;

@end
