/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUBonjourBrowser : NSObject {
    BOOL  _activateCalled;
    BOOL  _activated;
    struct BonjourBrowser { } * _bonjourBrowser;
    unsigned long long  _browseFlags;
    BOOL  _browseFlagsChanged;
    unsigned int  _changeFlags;
    unsigned int  _controlFlags;
    id  _deviceChangedHandler;
    id  _deviceFoundHandler;
    id  _deviceLostHandler;
    NSMutableDictionary * _deviceMap;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    NSString * _domain;
    NSString * _interfaceName;
    id  _interruptionHandler;
    BOOL  _invalidateCalled;
    BOOL  _invalidateDone;
    id  _invalidationHandler;
    NSString * _label;
    NSString * _serviceType;
    struct LogCategory { int x1; int x2; char *x3; unsigned int x4; char *x5; char *x6; int x7; struct LogCategory {} *x8; struct LogOutput {} *x9; struct LogOutput {} *x10; unsigned long long x11; unsigned long long x12; unsigned int x13; unsigned int x14; char *x15; struct LogCategoryPrivate {} *x16; } * _ucat;
}

@property (nonatomic) unsigned long long browseFlags;
@property (nonatomic) unsigned int changeFlags;
@property (nonatomic) unsigned int controlFlags;
@property (nonatomic, copy) id deviceChangedHandler;
@property (nonatomic, copy) id deviceFoundHandler;
@property (nonatomic, copy) id deviceLostHandler;
@property (readonly, copy) NSArray *devices;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (nonatomic, copy) NSString *domain;
@property (nonatomic, copy) NSString *interfaceName;
@property (nonatomic, copy) id interruptionHandler;
@property (nonatomic, copy) id invalidationHandler;
@property (nonatomic, copy) NSString *label;
@property (nonatomic, copy) NSString *serviceType;

- (void).cxx_destruct;
- (void)_activateSafeInvokeBlock:(id)arg1;
- (void)_bonjourHandleAddOrUpdateDevice:(id)arg1;
- (void)_bonjourHandleEventType:(unsigned int)arg1 info:(id)arg2;
- (void)_bonjourHandleRemoveDevice:(id)arg1;
- (int)_bonjourStart;
- (void)_interrupted;
- (void)_invalidated;
- (void)_lostAllDevices;
- (void)_update;
- (void)_updateLocked;
- (void)activate;
- (unsigned long long)browseFlags;
- (unsigned int)changeFlags;
- (unsigned int)controlFlags;
- (void)dealloc;
- (id)description;
- (id)descriptionWithLevel:(int)arg1;
- (id)deviceChangedHandler;
- (id)deviceFoundHandler;
- (id)deviceLostHandler;
- (id)devices;
- (id)dispatchQueue;
- (id)domain;
- (id)init;
- (id)interfaceName;
- (id)interruptionHandler;
- (void)invalidate;
- (id)invalidationHandler;
- (id)label;
- (id)serviceType;
- (void)setBrowseFlags:(unsigned long long)arg1;
- (void)setChangeFlags:(unsigned int)arg1;
- (void)setControlFlags:(unsigned int)arg1;
- (void)setDeviceChangedHandler:(id)arg1;
- (void)setDeviceFoundHandler:(id)arg1;
- (void)setDeviceLostHandler:(id)arg1;
- (void)setDispatchQueue:(id)arg1;
- (void)setDomain:(id)arg1;
- (void)setInterfaceName:(id)arg1;
- (void)setInterruptionHandler:(id)arg1;
- (void)setInvalidationHandler:(id)arg1;
- (void)setLabel:(id)arg1;
- (void)setServiceType:(id)arg1;
- (void)update;

@end
