/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUFileQuery : NSObject <CUDictionaryCodable> {
    id  _completionHandler;
    NSString * _path;
}

@property (nonatomic, copy) id completionHandler;
@property (nonatomic, copy) NSString *path;

- (void).cxx_destruct;
- (id)completionHandler;
- (id)description;
- (void)encodeWithDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1 error:(id*)arg2;
- (id)path;
- (void)setCompletionHandler:(id)arg1;
- (void)setPath:(id)arg1;

@end
