/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUHomeKitFindPairedPeerContext : NSObject {
    id  _completion;
    NSString * _identifier;
    unsigned long long  _options;
    CUPairedPeer * _pairedPeer;
    unsigned long long  _startTicks;
    BOOL  _triedAccessory;
    BOOL  _triedHAP;
    unsigned long long  _userCount;
    unsigned long long  _userIndex;
    NSArray * _users;
}

@property (nonatomic, copy) id completion;
@property (nonatomic, retain) NSString *identifier;
@property (nonatomic) unsigned long long options;
@property (nonatomic, retain) CUPairedPeer *pairedPeer;
@property (nonatomic) unsigned long long startTicks;
@property (nonatomic) BOOL triedAccessory;
@property (nonatomic) BOOL triedHAP;
@property (nonatomic) unsigned long long userCount;
@property (nonatomic) unsigned long long userIndex;
@property (nonatomic, retain) NSArray *users;

- (void).cxx_destruct;
- (id)completion;
- (id)identifier;
- (unsigned long long)options;
- (id)pairedPeer;
- (void)setCompletion:(id)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setOptions:(unsigned long long)arg1;
- (void)setPairedPeer:(id)arg1;
- (void)setStartTicks:(unsigned long long)arg1;
- (void)setTriedAccessory:(BOOL)arg1;
- (void)setTriedHAP:(BOOL)arg1;
- (void)setUserCount:(unsigned long long)arg1;
- (void)setUserIndex:(unsigned long long)arg1;
- (void)setUsers:(id)arg1;
- (unsigned long long)startTicks;
- (BOOL)triedAccessory;
- (BOOL)triedHAP;
- (unsigned long long)userCount;
- (unsigned long long)userIndex;
- (id)users;

@end
