/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUKeyValueStoreReader : NSObject {
    struct cdb { 
        char *map; 
        int fd; 
        unsigned int size; 
        unsigned int loop; 
        unsigned int khash; 
        unsigned int kpos; 
        unsigned int hpos; 
        unsigned int hslots; 
        unsigned int dpos; 
        unsigned int dlen; 
    }  _cdb;
    int  _fd;
    Class  _keyType;
    Class  _valueType;
}

- (id)_readObjectAtOffset:(unsigned int)arg1 length:(unsigned int)arg2 type:(Class)arg3 error:(id*)arg4;
- (void)close;
- (void)dealloc;
- (BOOL)enumerateKeyType:(Class)arg1 valueType:(Class)arg2 error:(id*)arg3 handler:(id)arg4;
- (BOOL)enumerateKeysAndValuesAndReturnError:(id*)arg1 handler:(id)arg2;
- (BOOL)enumerateValuesForKey:(id)arg1 error:(id*)arg2 handler:(id)arg3;
- (BOOL)enumerateValuesForKey:(id)arg1 valueType:(Class)arg2 error:(id*)arg3 handler:(id)arg4;
- (id)init;
- (id)initWithKeyType:(Class)arg1 valueType:(Class)arg2;
- (BOOL)openAtPath:(id)arg1 error:(id*)arg2;
- (BOOL)valueExistsForKey:(id)arg1;
- (id)valueForKey:(id)arg1 error:(id*)arg2;
- (id)valueForKey:(id)arg1 valueType:(Class)arg2 error:(id*)arg3;

@end
