/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CULiveAction : NSObject <CUActivatable, CUXPCCodable> {
    BOOL  _activateCalled;
    id  _activateCompletion;
    int  _alertType;
    BOOL  _clinkActivated;
    RPCompanionLinkClient * _clinkClient;
    RPCompanionLinkDevice * _clinkLocalDevice;
    NSArray * _destinationDevices;
    NSArray * _destinationIDs;
    BOOL  _direct;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    CUHomeKitManager * _homeKitManager;
    NSString * _homeKitSelfID;
    NSObject<OS_dispatch_source> * _homeKitTimer;
    BOOL  _invalidateCalled;
    BOOL  _invalidateDone;
    id  _invalidationHandler;
    NSString * _originatingHomeKitAccessoryID;
    NSMutableSet * _peerSessionSet;
    BOOL  _peersActivated;
    BOOL  _peersPerformDone;
    BOOL  _peersSetupDone;
    BOOL  _performLocally;
    BOOL  _prefStereoSpeak;
    NSMutableDictionary * _request;
    BOOL  _sentTimingInfo;
    int  _sessionState;
    NSURL * _soundFileURL;
    NSString * _speakText;
    NSObject<OS_os_transaction> * _transaction;
    BOOL  _xpcDone;
}

@property (nonatomic) int alertType;
@property (nonatomic, copy) NSArray *destinationIDs;
@property (nonatomic) BOOL direct;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (nonatomic, copy) id invalidationHandler;
@property (nonatomic, copy) NSString *originatingHomeKitAccessoryID;
@property (nonatomic, copy) NSURL *soundFileURL;
@property (nonatomic, copy) NSString *speakText;

- (void).cxx_destruct;
- (id)_findStereoCounterpart:(id)arg1;
- (void)_invalidate:(BOOL)arg1;
- (void)_invalidated;
- (void)_reportError:(id)arg1 where:(const char *)arg2;
- (void)_run;
- (void)_runCLinkActivateCompleted;
- (void)_runCLinkActivateStart;
- (void)_runCLinkPeersActivateStart;
- (void)_runCLinkPeersPerformStart;
- (void)_runCLinkPeersSetupStart;
- (void)_runFinish;
- (void)_runHomeKitStart;
- (BOOL)_runPrepareRequest;
- (void)_runXPCStart;
- (BOOL)_shouldPerformLocally;
- (void)activateWithCompletion:(id)arg1;
- (int)alertType;
- (id)destinationIDs;
- (BOOL)direct;
- (id)dispatchQueue;
- (void)encodeWithXPCObject:(id)arg1;
- (id)init;
- (id)initWithXPCObject:(id)arg1 error:(id*)arg2;
- (void)invalidate;
- (id)invalidationHandler;
- (id)originatingHomeKitAccessoryID;
- (void)setAlertType:(int)arg1;
- (void)setDestinationIDs:(id)arg1;
- (void)setDirect:(BOOL)arg1;
- (void)setDispatchQueue:(id)arg1;
- (void)setInvalidationHandler:(id)arg1;
- (void)setOriginatingHomeKitAccessoryID:(id)arg1;
- (void)setSoundFileURL:(id)arg1;
- (void)setSpeakText:(id)arg1;
- (id)soundFileURL;
- (id)speakText;

@end
