/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CULiveActionPeerSession : NSObject <CUActivatable> {
    RPCompanionLinkClient * _clinkClient;
    RPCompanionLinkDevice * _destinationDevice;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    id  _invalidationHandler;
    BOOL  _speakDisable;
}

@property (nonatomic, retain) RPCompanionLinkDevice *destinationDevice;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (nonatomic, copy) id invalidationHandler;
@property (nonatomic) BOOL speakDisable;

- (void).cxx_destruct;
- (void)activateWithCompletion:(id)arg1;
- (id)destinationDevice;
- (id)dispatchQueue;
- (void)invalidate;
- (id)invalidationHandler;
- (void)performRequest:(id)arg1 completion:(id)arg2;
- (void)setDestinationDevice:(id)arg1;
- (void)setDispatchQueue:(id)arg1;
- (void)setInvalidationHandler:(id)arg1;
- (void)setSpeakDisable:(BOOL)arg1;
- (void)setupWithRequest:(id)arg1 completion:(id)arg2;
- (BOOL)speakDisable;

@end
