/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUMessageSessionServer : NSObject <NSXPCListenerDelegate> {
    id  _deregisterRequestHandler;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    id  _invalidationHandler;
    id  _registerRequestHandler;
    id  _sendRequestHandler;
    CUMessageSession * _templateSession;
    NSMutableSet * _xpcConnections;
    NSXPCListenerEndpoint * _xpcEndpoint;
    NSXPCListener * _xpcListener;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic, copy) id deregisterRequestHandler;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) id invalidationHandler;
@property (nonatomic, copy) id registerRequestHandler;
@property (nonatomic, copy) id sendRequestHandler;
@property (readonly) Class superclass;
@property (nonatomic, retain) CUMessageSession *templateSession;

- (void).cxx_destruct;
- (void)_connectionInvalidated:(id)arg1;
- (void)activate;
- (id)deregisterRequestHandler;
- (id)dispatchQueue;
- (id)init;
- (void)invalidate;
- (id)invalidationHandler;
- (BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (id)registerRequestHandler;
- (id)sendRequestHandler;
- (void)setDeregisterRequestHandler:(id)arg1;
- (void)setDispatchQueue:(id)arg1;
- (void)setInvalidationHandler:(id)arg1;
- (void)setRegisterRequestHandler:(id)arg1;
- (void)setSendRequestHandler:(id)arg1;
- (void)setTemplateSession:(id)arg1;
- (id)templateSession;

@end
