/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUMFiWriteRequest : NSObject {
    id  _completion;
    NSData * _data;
    CUMFiWriteRequest * next;
}

@property (nonatomic, copy) id completion;
@property (nonatomic, retain) NSData *data;

- (void).cxx_destruct;
- (id)completion;
- (id)data;
- (void)setCompletion:(id)arg1;
- (void)setData:(id)arg1;

@end
