/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUNFCScanner : NSObject {
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    id  _foundDeviceHandler;
    id  _interruptionHandler;
    BOOL  _invalidateCalled;
    id  _invalidationHandler;
    id  _lostDeviceHandler;
    NSObject<OS_dispatch_queue> * _nfcDispatchQueue;
    BOOL  _pauseWhenFound;
}

@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (nonatomic, copy) id foundDeviceHandler;
@property (nonatomic, copy) id interruptionHandler;
@property (nonatomic, copy) id invalidationHandler;
@property (nonatomic, copy) id lostDeviceHandler;
@property (nonatomic) BOOL pauseWhenFound;

- (void).cxx_destruct;
- (void)_invalidateWithError:(id)arg1;
- (void)_pause;
- (void)activate;
- (id)dispatchQueue;
- (id)foundDeviceHandler;
- (id)init;
- (id)interruptionHandler;
- (void)invalidate;
- (id)invalidationHandler;
- (id)lostDeviceHandler;
- (void)pause;
- (BOOL)pauseWhenFound;
- (void)resume;
- (void)setDispatchQueue:(id)arg1;
- (void)setFoundDeviceHandler:(id)arg1;
- (void)setInterruptionHandler:(id)arg1;
- (void)setInvalidationHandler:(id)arg1;
- (void)setLostDeviceHandler:(id)arg1;
- (void)setPauseWhenFound:(BOOL)arg1;

@end
