/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUNFCDevice : NSObject {
    NSURL * _advertisedURI;
    NSUUID * _identifier;
}

@property (nonatomic, copy) NSURL *advertisedURI;
@property (nonatomic, copy) NSUUID *identifier;

- (void).cxx_destruct;
- (id)advertisedURI;
- (id)identifier;
- (void)setAdvertisedURI:(id)arg1;
- (void)setIdentifier:(id)arg1;

@end
