/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUOSRecoveryTarget : NSObject {
    BOOL  _activateCalled;
    CUBLEAdvertiser * _bleAdvertiser;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    BOOL  _invalidateCalled;
    BOOL  _invalidateDone;
    id  _progressHandler;
}

@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (nonatomic, copy) id progressHandler;

- (void).cxx_destruct;
- (void)_activate;
- (void)_invalidate;
- (void)_invalidated;
- (void)_reportProgressType:(int)arg1;
- (void)activate;
- (id)dispatchQueue;
- (id)init;
- (void)invalidate;
- (id)progressHandler;
- (void)setDispatchQueue:(id)arg1;
- (void)setProgressHandler:(id)arg1;

@end
