/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUPowerSourceMonitor : NSObject {
    BOOL  _activateCalled;
    NSMutableDictionary * _aggregateSources;
    unsigned int  _changeFlags;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    id  _invalidationHandler;
    NSMutableDictionary * _pendingAggregates;
    id  _powerSourceChangedHandler;
    id  _powerSourceFoundHandler;
    id  _powerSourceLostHandler;
    NSMutableDictionary * _powerSources;
    int  _psNotifyTokenAccessoryAttach;
    int  _psNotifyTokenAccessoryPowerSource;
    int  _psNotifyTokenAccessoryTimeRemaining;
    int  _psNotifyTokenAnyPowerSource;
}

@property (nonatomic) unsigned int changeFlags;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (nonatomic, copy) id invalidationHandler;
@property (nonatomic, copy) id powerSourceChangedHandler;
@property (nonatomic, copy) id powerSourceFoundHandler;
@property (nonatomic, copy) id powerSourceLostHandler;

- (void).cxx_destruct;
- (void)_aggregatePowerSourceFound:(id)arg1;
- (void)_aggregatePowerSourceLost:(id)arg1;
- (void)_aggregatePowerSourceUpdate:(id)arg1 changes:(unsigned int)arg2;
- (void)_cleanup;
- (void)_handlePowerSourceFound:(id)arg1 desc:(id)arg2 adapterDesc:(id)arg3;
- (void)_handlePowerSourceLost:(id)arg1 sourceID:(id)arg2;
- (void)_handlePowerSourceUpdate:(id)arg1 desc:(id)arg2 adapterDesc:(id)arg3;
- (void)_update;
- (void)_updatePowerSources;
- (void)activateWithCompletion:(id)arg1;
- (unsigned int)changeFlags;
- (void)dealloc;
- (id)dispatchQueue;
- (id)init;
- (void)invalidate;
- (id)invalidationHandler;
- (id)powerSourceChangedHandler;
- (id)powerSourceFoundHandler;
- (id)powerSourceLostHandler;
- (void)setChangeFlags:(unsigned int)arg1;
- (void)setDispatchQueue:(id)arg1;
- (void)setInvalidationHandler:(id)arg1;
- (void)setPowerSourceChangedHandler:(id)arg1;
- (void)setPowerSourceFoundHandler:(id)arg1;
- (void)setPowerSourceLostHandler:(id)arg1;

@end
