/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CURangingSession : NSObject {
    BOOL  _activateCalled;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    id  _errorHandler;
    unsigned int  _flags;
    BOOL  _invalidateCalled;
    BOOL  _invalidateDone;
    id  _invalidationHandler;
    NSString * _label;
    id  _measurementHandler;
    id  _measurementHandlerEx;
    NSArray * _peers;
    BOOL  _peersChanged;
    id  _statusChangedHandler;
    unsigned int  _statusFlags;
    struct LogCategory { int x1; int x2; char *x3; unsigned int x4; char *x5; char *x6; int x7; struct LogCategory {} *x8; struct LogOutput {} *x9; struct LogOutput {} *x10; unsigned long long x11; unsigned long long x12; unsigned int x13; unsigned int x14; char *x15; struct LogCategoryPrivate {} *x16; } * _ucat;
}

@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (nonatomic, copy) id errorHandler;
@property (nonatomic) unsigned int flags;
@property (nonatomic, copy) id invalidationHandler;
@property (nonatomic, copy) NSString *label;
@property (nonatomic, copy) id measurementHandler;
@property (nonatomic, copy) id measurementHandlerEx;
@property (nonatomic, copy) NSArray *peers;
@property (nonatomic, copy) id statusChangedHandler;
@property (nonatomic, readonly) unsigned int statusFlags;

- (void).cxx_destruct;
- (void)_invalidate;
- (void)_invalidated;
- (void)_update;
- (void)_updateInitiator;
- (void)_updatePeers;
- (void)_updateResponder;
- (void)activate;
- (void)addSample:(id)arg1;
- (void)dealloc;
- (id)dispatchQueue;
- (id)errorHandler;
- (unsigned int)flags;
- (id)init;
- (void)invalidate;
- (id)invalidationHandler;
- (id)label;
- (id)measurementHandler;
- (id)measurementHandlerEx;
- (id)peers;
- (void)setDispatchQueue:(id)arg1;
- (void)setErrorHandler:(id)arg1;
- (void)setFlags:(unsigned int)arg1;
- (void)setInvalidationHandler:(id)arg1;
- (void)setLabel:(id)arg1;
- (void)setMeasurementHandler:(id)arg1;
- (void)setMeasurementHandlerEx:(id)arg1;
- (void)setPeers:(id)arg1;
- (void)setStatusChangedHandler:(id)arg1;
- (id)statusChangedHandler;
- (unsigned int)statusFlags;

@end
