/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUReadRequest : NSObject {
    void * _bufferBytes;
    NSMutableData * _bufferData;
    char * _bufferPtr;
    id  _completion;
    NSData * _data;
    NSError * _error;
    BOOL  _hasMessageUUID;
    unsigned long long  _length;
    unsigned long long  _maxLength;
    unsigned char  _messageUUID;
    unsigned long long  _minLength;
    unsigned int  _statusFlags;
}

@property (nonatomic) void*bufferBytes;
@property (nonatomic, retain) NSMutableData *bufferData;
@property (nonatomic, copy) id completion;
@property (nonatomic, retain) NSData *data;
@property (nonatomic, readonly) NSError *error;
@property (nonatomic) BOOL hasMessageUUID;
@property (nonatomic, readonly) unsigned long long length;
@property (nonatomic) unsigned long long maxLength;
@property (nonatomic, readonly) char *messageUUID;
@property (nonatomic) unsigned long long minLength;
@property (nonatomic) unsigned int statusFlags;

- (void).cxx_destruct;
- (void*)bufferBytes;
- (id)bufferData;
- (id)completion;
- (id)data;
- (id)error;
- (BOOL)hasMessageUUID;
- (unsigned long long)length;
- (unsigned long long)maxLength;
- (char *)messageUUID;
- (unsigned long long)minLength;
- (void)setBufferBytes:(void*)arg1;
- (void)setBufferData:(id)arg1;
- (void)setCompletion:(id)arg1;
- (void)setData:(id)arg1;
- (void)setHasMessageUUID:(BOOL)arg1;
- (void)setMaxLength:(unsigned long long)arg1;
- (void)setMinLength:(unsigned long long)arg1;
- (void)setStatusFlags:(unsigned int)arg1;
- (unsigned int)statusFlags;

@end
