/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CURetrier : NSObject {
    id  _actionHandler;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    double  _interval;
    BOOL  _invalidateCalled;
    id  _invalidationHandler;
    double  _leeway;
    NSObject<OS_dispatch_source> * _retryTimer;
    double  _startTime;
}

@property (nonatomic, copy) id actionHandler;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (nonatomic) double interval;
@property (nonatomic, copy) id invalidationHandler;
@property (nonatomic) double leeway;
@property (nonatomic) double startTime;

- (void).cxx_destruct;
- (id)actionHandler;
- (id)dispatchQueue;
- (void)failed;
- (void)failedDirect;
- (id)init;
- (double)interval;
- (void)invalidate;
- (void)invalidateDirect;
- (id)invalidationHandler;
- (double)leeway;
- (void)setActionHandler:(id)arg1;
- (void)setDispatchQueue:(id)arg1;
- (void)setInterval:(double)arg1;
- (void)setInvalidationHandler:(id)arg1;
- (void)setLeeway:(double)arg1;
- (void)setStartTime:(double)arg1;
- (void)start;
- (void)startDirect;
- (double)startTime;
- (void)succeeded;
- (void)succeededDirect;

@end
