/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUSetupStepPreflightWiFi : CUSetupStep

- (BOOL)runAndReturnError:(id*)arg1;

@end
