/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUSetupStep : NSObject <CUActivatable, CUEnvironmentable> {
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    CUEnvironment * _environment;
    BOOL  _invalidateCalled;
    BOOL  _invalidateDone;
    id  _invalidationHandler;
    int  _runState;
    unsigned long long  _setupFlags;
    CUSetupFlow * _setupFlow;
}

@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (nonatomic, retain) CUEnvironment *environment;
@property (nonatomic, copy) id invalidationHandler;
@property (nonatomic) unsigned long long setupFlags;
@property (nonatomic, retain) CUSetupFlow *setupFlow;

- (void).cxx_destruct;
- (void)_activateWithCompletion:(id)arg1;
- (void)_invalidate;
- (void)_invalidated;
- (void)activateWithCompletion:(id)arg1;
- (id)dispatchQueue;
- (id)environment;
- (id)init;
- (void)invalidate;
- (id)invalidationHandler;
- (BOOL)run;
- (BOOL)runAndReturnError:(id*)arg1;
- (void)setDispatchQueue:(id)arg1;
- (void)setEnvironment:(id)arg1;
- (void)setInvalidationHandler:(id)arg1;
- (void)setSetupFlags:(unsigned long long)arg1;
- (void)setSetupFlow:(id)arg1;
- (unsigned long long)setupFlags;
- (id)setupFlow;

@end
