/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUSetupHandler : NSObject <CUActivatable, CUEnvironmentable> {
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    CUEnvironment * _environment;
    BOOL  _invalidateCalled;
    BOOL  _invalidateDone;
    id  _invalidationHandler;
}

@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (nonatomic, retain) CUEnvironment *environment;
@property (nonatomic, copy) id invalidationHandler;

- (void).cxx_destruct;
- (void)_activateWithCompletion:(id)arg1;
- (void)_invalidate;
- (void)_invalidated;
- (void)activateWithCompletion:(id)arg1;
- (id)dispatchQueue;
- (id)environment;
- (id)init;
- (void)invalidate;
- (id)invalidationHandler;
- (void)setDispatchQueue:(id)arg1;
- (void)setEnvironment:(id)arg1;
- (void)setInvalidationHandler:(id)arg1;

@end
