/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUSetupFlow : NSObject <CUActivatable, CUEnvironmentable> {
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    CUEnvironment * _environment;
    id  _errorHandler;
    BOOL  _invalidateCalled;
    BOOL  _invalidateDone;
    id  _invalidationHandler;
    CUEndpoint * _peerEndpoint;
    id  _runHandler;
    unsigned long long  _setupFlags;
    NSMutableArray * _stepArray;
}

@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (nonatomic, retain) CUEnvironment *environment;
@property (nonatomic, copy) id errorHandler;
@property (nonatomic, copy) id invalidationHandler;
@property (nonatomic, retain) CUEndpoint *peerEndpoint;
@property (nonatomic, copy) id runHandler;
@property (nonatomic) unsigned long long setupFlags;

- (void).cxx_destruct;
- (void)_activateWithCompletion:(id)arg1;
- (void)_invalidate;
- (void)_invalidated;
- (void)activateWithCompletion:(id)arg1;
- (void)addStep:(id)arg1;
- (id)dispatchQueue;
- (id)environment;
- (id)errorHandler;
- (id)init;
- (void)invalidate;
- (id)invalidationHandler;
- (id)peerEndpoint;
- (void)reportError:(id)arg1;
- (BOOL)run;
- (id)runHandler;
- (void)setDispatchQueue:(id)arg1;
- (void)setEnvironment:(id)arg1;
- (void)setErrorHandler:(id)arg1;
- (void)setInvalidationHandler:(id)arg1;
- (void)setPeerEndpoint:(id)arg1;
- (void)setRunHandler:(id)arg1;
- (void)setSetupFlags:(unsigned long long)arg1;
- (unsigned long long)setupFlags;

@end
