/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUSystemMonitorImp : NSObject <CXCallObserverDelegate, CoreTelephonyClientDelegate, FMFSessionDelegate> {
    int  _activeCallCount;
    struct { 
        unsigned char bytes[6]; 
    }  _bluetoothAddress48;
    NSData * _bluetoothAddressData;
    CUBluetoothClient * _bluetoothClient;
    TUCallCenter * _callCenter;
    unsigned int  _callFlags;
    CXCallObserver * _callObserver;
    BOOL  _callStatusObserving;
    BOOL  _clamshellMode;
    unsigned int  _clamshellNotification;
    struct IONotificationPort { } * _clamshellNotificationPort;
    int  _connectedCallCount;
    unsigned int  _consoleUserID;
    NSString * _consoleUserName;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    BOOL  _familyFailed;
    NSArray * _familyMembers;
    BOOL  _familyObserving;
    CUSystemMonitor * _familyPrimaryIPMonitor;
    int  _familyUpdatedToken;
    int  _firstUnlockToken;
    BOOL  _firstUnlocked;
    int  _fmfDevicesChangedToken;
    BOOL  _manateeAvailable;
    BOOL  _manateeObserving;
    int  _meDeviceChangedToken;
    NSString * _meDeviceFMFDeviceID;
    NSString * _meDeviceIDSDeviceID;
    BOOL  _meDeviceIsMe;
    NSString * _meDeviceName;
    int  _meDeviceRetryToken;
    BOOL  _meDeviceValid;
    NSMutableSet * _monitors;
    unsigned int  _netFlags;
    CUNetInterfaceMonitor * _netInterfaceMonitor;
    int  _powerSourceToken;
    BOOL  _powerUnlimited;
    NSString * _primaryAppleID;
    BOOL  _primaryAppleIDActive;
    BOOL  _primaryAppleIDIsHSA2;
    int  _primaryAppleIDNotifyToken;
    BOOL  _primaryAppleIDObserving;
    union { 
        struct sockaddr { 
            unsigned char sa_len; 
            unsigned char sa_family; 
            BOOL sa_data[14]; 
        } sa; 
        struct sockaddr_in { 
            unsigned char sin_len; 
            unsigned char sin_family; 
            unsigned short sin_port; 
            struct in_addr { 
                unsigned int s_addr; 
            } sin_addr; 
            BOOL sin_zero[8]; 
        } v4; 
        struct sockaddr_in6 { 
            unsigned char sin6_len; 
            unsigned char sin6_family; 
            unsigned short sin6_port; 
            unsigned int sin6_flowinfo; 
            struct in6_addr { 
                union { 
                    unsigned char __u6_addr8[16]; 
                    unsigned short __u6_addr16[8]; 
                    unsigned int __u6_addr32[4]; 
                } __u6_addr; 
            } sin6_addr; 
            unsigned int sin6_scope_id; 
        } v6; 
    }  _primaryIPv4Addr;
    union { 
        struct sockaddr { 
            unsigned char sa_len; 
            unsigned char sa_family; 
            BOOL sa_data[14]; 
        } sa; 
        struct sockaddr_in { 
            unsigned char sin_len; 
            unsigned char sin_family; 
            unsigned short sin_port; 
            struct in_addr { 
                unsigned int s_addr; 
            } sin_addr; 
            BOOL sin_zero[8]; 
        } v4; 
        struct sockaddr_in6 { 
            unsigned char sin6_len; 
            unsigned char sin6_family; 
            unsigned short sin6_port; 
            unsigned int sin6_flowinfo; 
            struct in6_addr { 
                union { 
                    unsigned char __u6_addr8[16]; 
                    unsigned short __u6_addr16[8]; 
                    unsigned int __u6_addr32[4]; 
                } __u6_addr; 
            } sin6_addr; 
            unsigned int sin6_scope_id; 
        } v6; 
    }  _primaryIPv6Addr;
    NSString * _primaryNetworkSignature;
    CoreTelephonyClient * _regionCTClient;
    struct __CTServerConnection { } * _regionCTServerCnx;
    NSString * _regionISOCountryCode;
    NSString * _regionMobileCountryCode;
    NSString * _regionRoutineCountry;
    RTRoutineManager * _regionRoutineManager;
    int  _regionRoutineNotifyToken;
    NSString * _regionRoutineState;
    struct { 
        unsigned char bytes[6]; 
    }  _rotatingIdentifier48;
    NSData * _rotatingIdentifierData;
    NSObject<OS_dispatch_source> * _rotatingIdentifierTimer;
    BOOL  _scChangesPending;
    struct __SCDynamicStore { } * _scDynamicStore;
    NSMutableArray * _scInitialKeys;
    NSString * _scKeyConsoleUser;
    NSString * _scKeySystemName;
    NSArray * _scNotificationKeys;
    NSArray * _scNotificationPatterns;
    NSString * _scPatternNetInterfaceIPv4;
    NSString * _scPatternNetInterfaceIPv6;
    BOOL  _screenLocked;
    int  _screenLockedToken;
    unsigned int  _screenNotification;
    struct IONotificationPort { } * _screenNotificationPort;
    BOOL  _screenOn;
    id  _screenSLSBlock;
    NSDictionary * _screenSLSDict;
    BOOL  _screenSLSInitial;
    BOOL  _screenSaverActive;
    int  _screenUnlockedToken;
    int  _systemLockState;
    int  _systemLockStateToken;
    NSString * _systemName;
    unsigned int  _wifiFlags;
    CUWiFiManager * _wifiManager;
    int  _wifiState;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (int)_activeCallCountUnached;
- (void)_bluetoothAddressMonitorStart;
- (void)_bluetoothAddressMonitorStop;
- (void)_callCenterStatusChanged:(id)arg1;
- (unsigned int)_callFlagsUncached;
- (void)_callInfoChanged;
- (void)_callMonitorStart;
- (void)_callMonitorStop;
- (void)_clamshellChangedWithService:(unsigned int)arg1 initial:(BOOL)arg2;
- (void)_clamshellMonitorStart;
- (void)_clamshellMonitorStop;
- (int)_connectedCallCountUnached;
- (void)_familyGetMembers:(BOOL)arg1;
- (void)_familyMonitorStart;
- (void)_familyMonitorStop;
- (void)_familyNetworkChanged;
- (void)_familyUpdated:(id)arg1;
- (void)_firstUnlockMonitorCheck:(BOOL)arg1;
- (void)_firstUnlockMonitorStart;
- (void)_firstUnlockMonitorStop;
- (BOOL)_hasMonitorPassingTest:(id)arg1;
- (void)_invokeBlock:(id)arg1 passingTest:(id)arg2;
- (void)_locationsOfInterestDidChange:(BOOL)arg1;
- (void)_manateeChanged:(id)arg1;
- (void)_manateeMonitorStart;
- (void)_manateeMonitorStop;
- (void)_meDeviceCheckCompletion:(id)arg1 error:(id)arg2 firstCheck:(BOOL)arg3;
- (void)_meDeviceCheckStart:(BOOL)arg1;
- (void)_meDeviceMonitorStart;
- (void)_meDeviceMonitorStop;
- (void)_netInterfaceMonitorStart;
- (void)_netInterfaceMonitorStop;
- (void)_powerUnlimitedMonitorStart;
- (void)_powerUnlimitedMonitorStop;
- (id)_primaryAppleIDAccount;
- (void)_primaryAppleIDChanged2:(BOOL)arg1;
- (void)_primaryAppleIDChanged:(id)arg1;
- (void)_primaryAppleIDMonitorStart;
- (void)_primaryAppleIDMonitorStop;
- (void)_regionMonitorGet;
- (void)_regionMonitorStart;
- (void)_regionMonitorStop;
- (void)_regionMonitorUpdateLocationsOfInterest:(id)arg1;
- (void)_regionMonitorUpdateMCC:(id)arg1;
- (void)_rotatingIdentifierMonitorStart;
- (void)_rotatingIdentifierMonitorStop;
- (void)_rotatingIdentifierTimerFired;
- (void)_screenChanged:(BOOL)arg1;
- (void)_screenLockedChanged;
- (void)_screenLockedMonitorStart;
- (void)_screenLockedMonitorStop;
- (void)_screenOnMonitorStart;
- (void)_screenOnMonitorStartDR;
- (int)_screenOnMonitorStartSLS;
- (void)_screenOnMonitorStop;
- (void)_screenSaverMonitorStart;
- (void)_screenSaverMonitorStop;
- (void)_systemConfigChanged:(id)arg1 initial:(BOOL)arg2;
- (void)_systemConfigConsoleUserChanged:(BOOL)arg1;
- (void)_systemConfigNetInterfaceChanged:(id)arg1 initial:(BOOL)arg2;
- (void)_systemConfigSystemNameChanged:(BOOL)arg1;
- (void)_systemConfigUpdateKeyPtr:(id*)arg1 name:(id)arg2 enabled:(BOOL)arg3 creator:(id)arg4;
- (void)_systemConfigUpdateNotifications;
- (void)_systemLockStateMonitorStart;
- (void)_systemLockStateMonitorStop;
- (void)_systemLockStateUpdate:(BOOL)arg1;
- (void)_update;
- (void)_wifiMonitorStart;
- (void)_wifiMonitorStateChanged:(BOOL)arg1;
- (void)_wifiMonitorStop;
- (void)addMonitor:(id)arg1 completion:(id)arg2;
- (void)callObserver:(id)arg1 callChanged:(id)arg2;
- (void)cellMonitorUpdate:(id)arg1 info:(id)arg2;
- (id)init;
- (void)removeMonitor:(id)arg1;
- (void)updateWithQueue:(id)arg1 completion:(id)arg2;

@end
