/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUUserNotificationCustomAction : NSObject {
    UNNotificationAction * _action;
    id  _handler;
}

@property (nonatomic, retain) UNNotificationAction *action;
@property (nonatomic, copy) id handler;

- (void).cxx_destruct;
- (id)action;
- (id)handler;
- (void)setAction:(id)arg1;
- (void)setHandler:(id)arg1;

@end
