/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUVoiceRequest : NSObject {
    id  _completion;
    unsigned int  _flags;
    id  _owner;
}

@property (nonatomic, copy) id completion;
@property (nonatomic) unsigned int flags;
@property (nonatomic, retain) id owner;

- (void).cxx_destruct;
- (id)completion;
- (unsigned int)flags;
- (id)owner;
- (void)setCompletion:(id)arg1;
- (void)setFlags:(unsigned int)arg1;
- (void)setOwner:(id)arg1;

@end
