/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
 */

@interface CUXPCAgent : NSObject <NSXPCListenerDelegate> {
    id  _connectionEndedHandler;
    id  _connectionStartedHandler;
    NSObject<OS_dispatch_queue> * _dispatchQueue;
    NSXPCInterface * _exportedInterface;
    id  _exportedObject;
    id  _interruptionHandler;
    BOOL  _invalidateCalled;
    BOOL  _invalidateDone;
    id  _invalidationHandler;
    NSString * _label;
    NSXPCListenerEndpoint * _listenerEndpoint;
    NSXPCInterface * _remoteObjectInterface;
    struct LogCategory { int x1; int x2; char *x3; unsigned int x4; char *x5; char *x6; int x7; struct LogCategory {} *x8; struct LogOutput {} *x9; struct LogOutput {} *x10; unsigned long long x11; unsigned long long x12; unsigned int x13; unsigned int x14; char *x15; struct LogCategoryPrivate {} *x16; } * _ucat;
    NSXPCConnection * _xpcCnx;
    NSMutableSet * _xpcCnxSet;
    NSXPCListener * _xpcListener;
}

@property (nonatomic, copy) id connectionEndedHandler;
@property (nonatomic, copy) id connectionStartedHandler;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (nonatomic, retain) NSXPCInterface *exportedInterface;
@property (nonatomic, retain) id exportedObject;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) id interruptionHandler;
@property (nonatomic, copy) id invalidationHandler;
@property (nonatomic, copy) NSString *label;
@property (nonatomic, retain) NSXPCListenerEndpoint *listenerEndpoint;
@property (nonatomic, retain) NSXPCInterface *remoteObjectInterface;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_connectionInvalidated:(id)arg1;
- (void)_interrupted;
- (void)_invalidate;
- (void)_invalidated;
- (BOOL)activateDirectAndReturnError:(id*)arg1;
- (void)activateWithCompletion:(id)arg1;
- (id)connectionEndedHandler;
- (id)connectionStartedHandler;
- (void)dealloc;
- (id)dispatchQueue;
- (id)exportedInterface;
- (id)exportedObject;
- (id)init;
- (id)interruptionHandler;
- (void)invalidate;
- (id)invalidationHandler;
- (id)label;
- (BOOL)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (id)listenerEndpoint;
- (id)remoteObjectInterface;
- (id)remoteObjectProxy;
- (id)remoteObjectProxyWithErrorHandler:(id)arg1;
- (void)setConnectionEndedHandler:(id)arg1;
- (void)setConnectionStartedHandler:(id)arg1;
- (void)setDispatchQueue:(id)arg1;
- (void)setExportedInterface:(id)arg1;
- (void)setExportedObject:(id)arg1;
- (void)setInterruptionHandler:(id)arg1;
- (void)setInvalidationHandler:(id)arg1;
- (void)setLabel:(id)arg1;
- (void)setListenerEndpoint:(id)arg1;
- (void)setRemoteObjectInterface:(id)arg1;

@end
